### ISSUE TITLE
Update document of recording VCR tests.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-python-devtools#6]
https://github.com/Azure/azure-python-devtools/blob/master/doc/recording_vcr_tests.md

**Comment by v-iam** [comment]
Started looking into doing this. A couple thoughts:
* I think the doc you linked is more or less defunct, since it refers to the old version of the test framework that this repo is based on. https://github.com/Azure/azure-python-devtools/blob/master/doc/scenario_base_tests.md seems like a better starting point.
* The samples in that scenario_base_tests.md are all CLI-based so don't really have a straightforward analog now that this framework is no longer CLI-centric (and `cmd` has been moved into the `azure-cli` wrappers). Need to think about how to frame samples so that they demonstrate the functionality without being too complicated or introducing other dependencies.

**Comment by v-iam** [comment]
All the test examples in `scenario_base_tests.md` should still work unchanged and are still in the `azure-cli` doc of the same name. I am thinking maybe I should just remove those examples from this repo since they are CLI-specific, add a link to the `azure-cli` doc so that concrete examples are still available, and add some information about subclassing `ReplayableTest` and `AbstractPreparer` for different use cases.

**Comment by v-iam** [comment]
I think #19 resolves this?

**Comment by troydai** [comment]
Oh, yeah.
