### ISSUE TITLE
create_random_name might not work well

### ISSUE THREAD

**Issue by v-iam** [Azure/azure-python-devtools#9]
As it stands, the two consumers of `azure-devtools` both override `ReplayableTest.create_random_name`, which is good because I think the default implementation might not work.

In particular, due to this line in `azure_devtools.scenario_tests.utilities.create_random_name` (which `IntegrationTestBase.create_random_name` calls):
``` python
random_bytes = os.urandom(int(math.ceil(float(padding_size) / 8) * 5))
```

the names it generates will be actually random and not consistent between test runs. (I haven't yet tested this but I can't see how it would be otherwise. This would also be a prime candidate for #5 as well.)

**Comment by v-iam** [comment]
I think a good way to resolve this would be to pull azure-sdk-for-python's name generation up into azure-python-devtools.

The SDK gets resource names by taking a name prefix and adding a checksum based on the fully qualified test name (i.e. `module_name.test_name`).
The qualified test name is determined here: https://github.com/Azure/azure-sdk-for-python/blob/v2.0.0rc6/azure-common/testutils/common_recordingtestcase.py#L51
and it's combined with the checksum here: https://github.com/Azure/azure-sdk-for-python/blob/v2.0.0rc6/azure-common/testutils/common_recordingtestcase.py#L97

This should be a general enough approach to go in azure-devtools, and as @lmazuel pointed out it has the additional advantage of allowing the user to change the order in which resources are created without breaking tests. The CLI's "count resources" approach does not have that property.

**Comment by troydai** [comment]
The method is designed with the intention to be truly random, therefore it use `os.urandom` under the hood. If the goal is somehow to create a pseudo-random sequence then the mechanism should be implemented in another method.

Test and test framework must not rely on any repeatable random value between test runs. There is an existing mechanism in place to replace the random value with ordered, replayable moniker in recordings. Any attempt to replace it may compromise the parallel run because the duplicate names may prevent the live test from being successful.

**Comment by v-iam** [comment]
I see. I didn't have the distinction between the moniker used in recordings and the random name used for actual server interactions clear in my mind. Thanks for the clarification.
